### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by andysingal** [cg123/mergekit#122]
<img width="454" alt="Screenshot 2024-01-20 at 5 37 31 PM" src="https://github.com/cg123/mergekit/assets/20493493/9272b246-7323-4f0e-b17d-f36dd0b9bb2d">

giving error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires openai, which is not installed.
llmx 0.0.15a0 requires tiktoken, which is not installed.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.9.0 which is incompatible.
mergekit-yaml config.yaml merge --copy-tokenizer --cuda --low-cpu-memory --trust-remote-code
config.json: 100% 720/720 [00:00<00:00, 4.22MB/s]
Traceback (most recent call last):
  File "/usr/local/bin/mergekit-yaml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/mergekit/mergekit/options.py", line 59, in wrapper
    f(*args, **kwargs)
  File "/content/mergekit/mergekit/scripts/run_yaml.py", line 47, in main
    run_merge(
  File "/content/mergekit/mergekit/merge.py", line 70, in run_merge
    model_arch_info = [
  File "/content/mergekit/mergekit/merge.py", line 71, in <listcomp>
    get_architecture_info(m.config(trust_remote_code=options.trust_remote_code))
  File "/content/mergekit/mergekit/common.py", line 75, in config
    return AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1064, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 761, in __getitem__
    raise KeyError(key)
KeyError: 'mixtral'
```

**Comment by AliHaider20** [comment]
Your transformer version should be latest for using the Mistral model.

**Comment by cg123** [comment]
If you run `pip install -U transformers` this error should be resolved.
