### ISSUE TITLE
While quantized by awq , error  KeyError: 'block_sparse_moe.experts.0.w2'`

### ISSUE THREAD

**Issue by xiechengmude** [cg123/mergekit#63]
`Fetching 31 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 101739.77it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [02:16<00:00,  5.95s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/huggingface_hub/repocard.py:105: UserWarning: Repo card metadata block was not found. Setting CardData to empty.
  warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")
Token indices sequence length is longer than the specified maximum sequence length for this model (8947 > 4096). Running this sequence through the model will result in indexing errors
AWQ:   3%|████▉                                                                                                                                               | 2/60 [02:42<1:18:35, 81.31s/it]
Traceback (most recent call last):
  File "/workspace/AutoAWQ/examples/mixtral_quant2.py", line 23, in <module>
    model.quantize(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/awq/models/base.py", line 93, in quantize
    quantizer.quantize()
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/awq/quantize/quantizer.py", line 99, in quantize
    module_config: List[Dict] = self.awq_model.get_layers_for_scaling(
  File "/root/miniconda3/envs/mergekit/lib/python3.10/site-packages/awq/models/mixtral.py", line 74, in get_layers_for_scaling
    inp=input_feat[f'block_sparse_moe.experts.{i}.w2'],
KeyError: 'block_sparse_moe.experts.0.w2'`

**Comment by cg123** [comment]
Could you give some more details please? I suspect this is #50, so it would be helpful to know how the model was configured.

**Comment by xiechengmude** [comment]
yes. I try to quantize it with autoawq.  Its a mixtral model based on several 34b yi  finetuned models.
